/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewFuncionario;

import ControllerFuncionario.ValidacionesController;
import Method.funcionario.CheckOutMethod;
import Model.Funcionario.CheckOut;
import Model.Funcionario.Usuario;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alx4a
 */
public class CheckOutView extends javax.swing.JFrame {
    CheckOutMethod com = new CheckOutMethod();
    CheckOut co = new CheckOut();
    ValidacionesController vc = new ValidacionesController();
    Usuario u = new Usuario();
    /**
     * Creates new form CheckOutView
     */
    public CheckOutView() {
        initComponents();
        setLocationRelativeTo(null);
        com.listarReservaCheckOut(JTableCheckOut);
        txtFechaSalida.setText(vc.fechaActual());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        JTableCheckOut = new javax.swing.JTable();
        txtBuscarRut = new javax.swing.JTextField();
        btnBuscarRut = new javax.swing.JButton();
        btnIngresarCheckOut = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblMultas = new javax.swing.JLabel();
        lblCostoReparacion = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtMultas = new javax.swing.JTextField();
        txtCostoReparacion = new javax.swing.JTextField();
        txtFechaSalida = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtComentarios = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        JTableCheckOut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTableCheckOut);

        txtBuscarRut.setText("Rut...");
        txtBuscarRut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBuscarRutMouseClicked(evt);
            }
        });

        btnBuscarRut.setText("Buscar");
        btnBuscarRut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRutActionPerformed(evt);
            }
        });

        btnIngresarCheckOut.setText("Ingresar Check Out");
        btnIngresarCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarCheckOutActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblMultas.setText("Multas");

        lblCostoReparacion.setText("Costo Reparación");

        lblFecha.setText("Fecha");

        lblDescripcion.setText("Comentarios");

        txtFechaSalida.setEnabled(false);

        txtComentarios.setColumns(20);
        txtComentarios.setRows(5);
        jScrollPane3.setViewportView(txtComentarios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscarRut))
                    .addComponent(btnVolver)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCostoReparacion)
                            .addComponent(lblMultas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCostoReparacion, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                            .addComponent(txtMultas))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDescripcion)
                            .addComponent(lblFecha))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIngresarCheckOut)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarRut)
                    .addComponent(txtBuscarRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCostoReparacion)
                    .addComponent(txtCostoReparacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha)
                    .addComponent(txtFechaSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescripcion)
                            .addComponent(lblMultas)
                            .addComponent(txtMultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(btnIngresarCheckOut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVolver)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
        MenuFuncionario mf = new MenuFuncionario();
        mf.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnIngresarCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarCheckOutActionPerformed
 DefaultTableModel model = (DefaultTableModel) JTableCheckOut.getModel();
        boolean resultado = false;
        int fila = JTableCheckOut.getSelectedRow();
        try {
            
            if (resultado == false) {
                if (fila < 0) {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar una fila para poder ingresar el check in");
                    resultado = true;
                }
            }
            //guardo el texto de multas
            int multa = Integer.parseInt(txtMultas.getText());
            
            //guardo el texto de costo reparacion
            int costoReparacion = Integer.parseInt(txtCostoReparacion.getText());
          
            String f = String.valueOf(model.getValueAt(JTableCheckOut.getSelectedRow(), 3));
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            Date fecha = formato.parse(f);
            
            String r = String.valueOf(model.getValueAt(JTableCheckOut.getSelectedRow(), 1));
            int idReserva = Integer.parseInt(r);
            
            String d = String.valueOf(model.getValueAt(JTableCheckOut.getSelectedRow(), 2));
            int idDepa = Integer.parseInt(d);
            if (!txtMultas.getText().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(this, "Solo se pueden ingresar numeros en el campo multas");
                resultado = true;
            }
            if (!txtCostoReparacion.getText().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(this, "Solo se pueden ingresar numeros en el campo costo reparacion");
                resultado = true;
            }
            String comentarios = txtComentarios.getText();
            if (comentarios.equals("")) {
                JOptionPane.showMessageDialog(this, "El campo comentarios no puede quedar vacio");
                resultado = true;
            }
            if (resultado == false) {
                com.insertarCheckOut(multa, costoReparacion, txtComentarios, fecha, idReserva, idDepa);
                System.out.println("se ingreso el check_out");
                com.listarReservaCheckOut(JTableCheckOut);
                CheckListView clv = new CheckListView();
                clv.btnVolver.setEnabled(false);
                clv.setVisible(true);
                this.dispose();
            }
            
            
            
        } catch (Exception e) {
            System.out.println("no se ingreso checkout"+ e.getMessage());
        }
        
    }//GEN-LAST:event_btnIngresarCheckOutActionPerformed

    private void txtBuscarRutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBuscarRutMouseClicked
        String text = txtBuscarRut.getText();
        if (text.equals("Rut...")) {
            txtBuscarRut.setText("");
        }
    }//GEN-LAST:event_txtBuscarRutMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
         String text = txtBuscarRut.getText();
        if (text.equals("")) {
            txtBuscarRut.setText("Rut...");
        }
    }//GEN-LAST:event_formMouseClicked

    private void btnBuscarRutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRutActionPerformed
        u.setRutUsuario(txtBuscarRut.getText());
        String rut = txtBuscarRut.getText();
        boolean r = false;
        
        if (!txtBuscarRut.getText().matches("\\b(\\d{1,3}(?:(\\.?)\\d{3}){2}(-)[\\dkK])\\b")) {
           JOptionPane.showMessageDialog(this, "El rut que buscas puede ser con o sin puntos, pero tiene que llevar guion");
           r = true;
        }
 
        if (rut.equals("")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un rut para poder buscar");
            r = true;
        }
        
        if (rut.equals("Rut...")) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un rut para poder buscar");
            r = true;
        } 
        
        if (r = false) {
           com.listarReservaCheckOutPorRut(txtBuscarRut, JTableCheckOut); 
        }
    }//GEN-LAST:event_btnBuscarRutActionPerformed

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckOutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckOutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckOutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckOutView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckOutView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableCheckOut;
    private javax.swing.JButton btnBuscarRut;
    private javax.swing.JButton btnIngresarCheckOut;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCostoReparacion;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblMultas;
    private javax.swing.JTextField txtBuscarRut;
    private javax.swing.JTextArea txtComentarios;
    private javax.swing.JTextField txtCostoReparacion;
    private javax.swing.JTextField txtFechaSalida;
    private javax.swing.JTextField txtMultas;
    // End of variables declaration//GEN-END:variables
}
