/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewFuncionario;


import ControllerFuncionario.CheckListController;
import Method.funcionario.CheckListMethod;
import Model.Funcionario.Departamento;
import Model.Funcionario.DetalleHabitacion;
import Model.Funcionario.Habitacion;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alx4a
 */
public class CheckListView extends javax.swing.JFrame {
    ArrayList<Departamento> dep = new ArrayList<Departamento>();
    Habitacion estado = new Habitacion();
    CheckListController clc = new CheckListController();
    Habitacion h = new Habitacion();
    DetalleHabitacion detalleHabitacion = new DetalleHabitacion();
    CheckListMethod clm = new CheckListMethod();
    
    /**
     * Creates new form CheckListView
     */
    public CheckListView() {
        initComponents();
        setLocationRelativeTo(null);
        CheckListController clc = new CheckListController();
        dep = clc.arrayListDepartamento();
        DefaultTableModel table = new DefaultTableModel();
        table = clc.updateTableCheckList(dep);
        jTableDepartamentos.setModel(table);
        btnCreateCheckList.setEnabled(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCreateCheckList = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDepartamentos = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        lblEstadoDepartamento = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAestadoDepartamento = new javax.swing.JTextArea();
        btnIngresarEstadoDepartamento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCreateCheckList.setText("Crear Checklist");
        btnCreateCheckList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateCheckListActionPerformed(evt);
            }
        });

        jTableDepartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableDepartamentos);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        lblEstadoDepartamento.setText("Estado del Departamento");

        txtAestadoDepartamento.setColumns(20);
        txtAestadoDepartamento.setRows(5);
        jScrollPane2.setViewportView(txtAestadoDepartamento);

        btnIngresarEstadoDepartamento.setText("Ingresar Estado");
        btnIngresarEstadoDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarEstadoDepartamentoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lblEstadoDepartamento)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnIngresarEstadoDepartamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCreateCheckList)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 976, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnVolver)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCreateCheckList)
                        .addComponent(btnIngresarEstadoDepartamento))
                    .addComponent(lblEstadoDepartamento)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateCheckListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateCheckListActionPerformed
        int fila = jTableDepartamentos.getSelectedRow();
        DefaultTableModel table = (DefaultTableModel) jTableDepartamentos.getModel();
        
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un departamento para poder crear el CheckList");   
        }
        else{
            String estado = String.valueOf(table.getValueAt(jTableDepartamentos.getSelectedRow(), 3));
            if (estado.equals("Ocupado")) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un departamento disponible o reservado");
            }
            if (estado.equals("En Mantencion")) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un departamento disponible o reservado");
            }
            else{
              String de = String.valueOf(table.getValueAt(jTableDepartamentos.getSelectedRow(), 0));
              int iddep = Integer.parseInt(de);
              
              this.dispose();
              CheckListViewSubView clvs = new CheckListViewSubView(iddep);
              clvs.setVisible(true);  
            }
            
            
        }
    }//GEN-LAST:event_btnCreateCheckListActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
        MenuFuncionario mf = new MenuFuncionario();
        mf.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnIngresarEstadoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarEstadoDepartamentoActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableDepartamentos.getModel();
        int fila = jTableDepartamentos.getSelectedRow();
        if (fila < 0) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una fila para poder ingresar el estado");
        }
        else{
            String estado = String.valueOf(model.getValueAt(jTableDepartamentos.getSelectedRow(), 3));
            if (estado.equals("Ocupado")) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un departamento disponible o reservado");
            }
            if (estado.equals("En Mantencion")) {
                JOptionPane.showMessageDialog(this, "Debes seleccionar un departamento disponible o reservado");
            }
            else{
            //guardo el id de departamento en una variable int
            String idFila = String.valueOf(model.getValueAt(jTableDepartamentos.getSelectedRow(), 0));
            int idDep = Integer.parseInt(idFila);
            h.setEstadoHabitacion(txtAestadoDepartamento.getText());
            clm.actualizarEstadoDepartamento(txtAestadoDepartamento, idDep);
            btnCreateCheckList.setEnabled(true);
            JOptionPane.showMessageDialog(this, "Exito");
            }
        }       
            
       
        
    }//GEN-LAST:event_btnIngresarEstadoDepartamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CheckListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CheckListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CheckListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CheckListView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CheckListView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateCheckList;
    private javax.swing.JButton btnIngresarEstadoDepartamento;
    public javax.swing.JButton btnVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDepartamentos;
    private javax.swing.JLabel lblEstadoDepartamento;
    private javax.swing.JTextArea txtAestadoDepartamento;
    // End of variables declaration//GEN-END:variables
}
