/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewFuncionario;

/**
 *
 * @author alx4a
 */
public class MenuFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form MenuFuncionario
     */
    public MenuFuncionario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jProcesos = new javax.swing.JMenu();
        jMenuCheckIn = new javax.swing.JMenuItem();
        jMenuCheckOut = new javax.swing.JMenuItem();
        jMenuCheckList = new javax.swing.JMenuItem();
        jSession = new javax.swing.JMenu();
        jMenuCerrarSesion = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jProcesos.setText("Procesos");

        jMenuCheckIn.setText("Check In");
        jMenuCheckIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCheckInActionPerformed(evt);
            }
        });
        jProcesos.add(jMenuCheckIn);

        jMenuCheckOut.setText("Check Out");
        jMenuCheckOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCheckOutActionPerformed(evt);
            }
        });
        jProcesos.add(jMenuCheckOut);

        jMenuCheckList.setText("Checklist Inventario");
        jMenuCheckList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCheckListActionPerformed(evt);
            }
        });
        jProcesos.add(jMenuCheckList);

        jMenuBar1.add(jProcesos);

        jSession.setText("Sesión");

        jMenuCerrarSesion.setText("Cerrar sesión");
        jMenuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCerrarSesionActionPerformed(evt);
            }
        });
        jSession.add(jMenuCerrarSesion);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jSession.add(jMenuSalir);

        jMenuBar1.add(jSession);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCheckListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCheckListActionPerformed
        this.dispose();
        CheckListView clv = new CheckListView();
        clv.setVisible(true);
    }//GEN-LAST:event_jMenuCheckListActionPerformed

    private void jMenuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCerrarSesionActionPerformed
        this.dispose();
        //Login lgn = new Login();
        //lgn.setVisible(true);
    }//GEN-LAST:event_jMenuCerrarSesionActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jMenuCheckInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCheckInActionPerformed
        this.dispose();
        CheckInView civ = new CheckInView();
        civ.setVisible(true);
    }//GEN-LAST:event_jMenuCheckInActionPerformed

    private void jMenuCheckOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCheckOutActionPerformed
        this.dispose();
        CheckOutView cov = new CheckOutView();
        cov.setVisible(true);
    }//GEN-LAST:event_jMenuCheckOutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCerrarSesion;
    private javax.swing.JMenuItem jMenuCheckIn;
    private javax.swing.JMenuItem jMenuCheckList;
    private javax.swing.JMenuItem jMenuCheckOut;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenu jProcesos;
    private javax.swing.JMenu jSession;
    // End of variables declaration//GEN-END:variables
}
