/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Method.ServiciosMethod;
import javax.swing.JOptionPane;

/**
 *
 * @author thoma
 */
public class vistaServiciosExtras extends javax.swing.JFrame {

    ServiciosMethod sm = new ServiciosMethod();

    public vistaServiciosExtras() {
        initComponents();
        setLocationRelativeTo(null);
        sm.cargarTablaServicios(tablaServiciosExtra);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreServicio = new javax.swing.JTextField();
        txtCostoServicio = new javax.swing.JTextField();
        scroll = new javax.swing.JScrollPane();
        tablaServiciosExtra = new javax.swing.JTable();
        btonAgregarServicio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIDServicio = new javax.swing.JTextField();
        btonEliminarServicio = new javax.swing.JButton();
        btonActualizarServicio = new javax.swing.JButton();
        btonActualizarTablaServicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jLabel1.setText("Nombre Servicio");

        jLabel2.setText("Costo");

        tablaServiciosExtra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaServiciosExtra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaServiciosExtraMouseClicked(evt);
            }
        });
        scroll.setViewportView(tablaServiciosExtra);

        btonAgregarServicio.setText("Agregar");
        btonAgregarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonAgregarServicioActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Servicio");

        btonEliminarServicio.setText("Eliminar");
        btonEliminarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonEliminarServicioActionPerformed(evt);
            }
        });

        btonActualizarServicio.setText("Actualizar");
        btonActualizarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonActualizarServicioActionPerformed(evt);
            }
        });

        btonActualizarTablaServicio.setText("Actualizar");
        btonActualizarTablaServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonActualizarTablaServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scroll)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(txtCostoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreServicio)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIDServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(475, 475, 475))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(btonAgregarServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btonActualizarServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btonEliminarServicio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btonActualizarTablaServicio)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIDServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCostoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btonAgregarServicio)
                    .addComponent(btonEliminarServicio)
                    .addComponent(btonActualizarServicio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(btonActualizarTablaServicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btonAgregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonAgregarServicioActionPerformed
        if (txtNombreServicio.getText().equals("") || txtCostoServicio.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
        } else {
            sm.agregarServicio(txtNombreServicio, txtCostoServicio);
            sm.cargarTablaServicios(tablaServiciosExtra);
        }

    }//GEN-LAST:event_btonAgregarServicioActionPerformed

    private void btonActualizarTablaServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonActualizarTablaServicioActionPerformed
        sm.cargarTablaServicios(tablaServiciosExtra);
    }//GEN-LAST:event_btonActualizarTablaServicioActionPerformed

    private void btonActualizarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonActualizarServicioActionPerformed
        if (txtIDServicio.getText().equals("") || txtNombreServicio.getText().equals("") || txtCostoServicio.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos");
        } else {
            sm.ActualizarServicio(txtIDServicio, txtNombreServicio, txtCostoServicio);
            sm.cargarTablaServicios(tablaServiciosExtra);
        }

    }//GEN-LAST:event_btonActualizarServicioActionPerformed

    private void btonEliminarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonEliminarServicioActionPerformed
        if (txtIDServicio.getText() == "" || txtIDServicio.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un ID");
        } else {
            sm.EliminarServicio(txtIDServicio);
            sm.cargarTablaServicios(tablaServiciosExtra);
        }

    }//GEN-LAST:event_btonEliminarServicioActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

    }//GEN-LAST:event_formMouseClicked

    private void tablaServiciosExtraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaServiciosExtraMouseClicked
                int fila = tablaServiciosExtra.getSelectedRow();
        String codigo = tablaServiciosExtra.getValueAt(fila, 0).toString();
        
        sm.PasarDatosTablasACampos(codigo, txtIDServicio, txtNombreServicio, txtCostoServicio);
    }//GEN-LAST:event_tablaServiciosExtraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaServiciosExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaServiciosExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaServiciosExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaServiciosExtras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaServiciosExtras().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btonActualizarServicio;
    private javax.swing.JButton btonActualizarTablaServicio;
    private javax.swing.JButton btonAgregarServicio;
    private javax.swing.JButton btonEliminarServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tablaServiciosExtra;
    private javax.swing.JTextField txtCostoServicio;
    private javax.swing.JTextField txtIDServicio;
    private javax.swing.JTextField txtNombreServicio;
    // End of variables declaration//GEN-END:variables
}
