/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Method.DepartamentosMethod;
import Model.Comuna;
import Model.Provincia;
import Model.Region;
import java.awt.event.ItemEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author thoma
 */
public class VistaDepartamentos extends javax.swing.JFrame {

    DepartamentosMethod dm = new DepartamentosMethod();

    /**
     * Creates new form VistaDepartamentos
     */
    public VistaDepartamentos() {
        initComponents();
        setLocationRelativeTo(null);
        //mostrarComboBoxDepartamento();
        mostrarComboRegiones();
        dm.cargarTablaDepartamentos(tablaDepartamentos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        cmBoxRegion = new javax.swing.JComboBox<>();
        btnCargarTabla = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtIdDepartmaneto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        cmBoxProvincia = new javax.swing.JComboBox<>();
        txtCosto = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        cmBoxComuna = new javax.swing.JComboBox<>();
        txtDescripcion = new javax.swing.JTextField();
        btonAgregarDepartamento = new javax.swing.JButton();
        txtEstacionamiento = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtOrientacion = new javax.swing.JTextField();
        btonActualizarDepartamento = new javax.swing.JButton();
        txtNumHabitaciones = new javax.swing.JTextField();
        txtNumBaños = new javax.swing.JTextField();
        btonEliminarDepartamento = new javax.swing.JButton();
        txtNumEstacionamientos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDepartamentos = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtDividendo = new javax.swing.JTextField();
        txtContribucion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel10.setText("numEstacionamientos");

        cmBoxRegion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmBoxRegionItemStateChanged(evt);
            }
        });

        btnCargarTabla.setText("Refrescar Tabla");
        btnCargarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarTablaActionPerformed(evt);
            }
        });

        jLabel11.setText("Region");

        jLabel12.setText("Provincia");

        cmBoxProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmBoxProvinciaItemStateChanged(evt);
            }
        });

        jLabel13.setText("Comuna");

        btonAgregarDepartamento.setText("Agregar");
        btonAgregarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonAgregarDepartamentoActionPerformed(evt);
            }
        });

        jLabel14.setText("Acciones");

        btonActualizarDepartamento.setText("Actualizar");
        btonActualizarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonActualizarDepartamentoActionPerformed(evt);
            }
        });

        btonEliminarDepartamento.setText("Eliminar");
        btonEliminarDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btonEliminarDepartamentoActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Direccion");

        jLabel3.setText("Costo");

        jLabel4.setText("Estado");

        jLabel5.setText("Descripcion");

        jLabel6.setText("Orientacion");

        jLabel7.setText("Estacionamiento");

        jLabel8.setText("numHabitaciones");

        jLabel9.setText("NumBaños");

        tablaDepartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Direccion", "Costo", "Estado", "Descripcion", "Orientacion", "Estacionamiento", "NumHabitaciones", "NumBaños", "NumEstacionamiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDepartamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDepartamentosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDepartamentos);

        jLabel15.setText("Dividendo");

        jLabel16.setText("Contribucion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1138, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtEstado)
                                    .addComponent(txtIdDepartmaneto)
                                    .addComponent(txtCosto)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnCargarTabla)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEstacionamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtOrientacion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtNumHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel14))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btonAgregarDepartamento)
                                                .addGap(18, 18, 18)
                                                .addComponent(btonActualizarDepartamento)))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btonEliminarDepartamento)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNumEstacionamientos, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                            .addComponent(txtNumBaños, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                            .addComponent(cmBoxRegion, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmBoxProvincia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(26, 26, 26)
                                                .addComponent(cmBoxComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel16)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtContribucion))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addComponent(jLabel15)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(txtDividendo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addGap(0, 171, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdDepartmaneto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumBaños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13)
                    .addComponent(cmBoxComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtOrientacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumEstacionamientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel10)
                    .addComponent(jLabel15)
                    .addComponent(txtDividendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstacionamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmBoxRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel16)
                            .addComponent(txtContribucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(cmBoxProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarTabla)
                    .addComponent(btonAgregarDepartamento)
                    .addComponent(jLabel14)
                    .addComponent(btonActualizarDepartamento)
                    .addComponent(btonEliminarDepartamento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/*private void mostrarComboBoxDepartamento(){
        dm.mostrarCmbxComunas(cmBoxComuna);
        dm.mostrarCmbxProvincias(cmBoxProvincia);
}*/
    private void mostrarComboRegiones() {
        DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel(dm.mostrarRegiones());
        cmBoxRegion.setModel(modeloCombo);
    }

    private void tablaDepartamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDepartamentosMouseClicked
        int fila = tablaDepartamentos.getSelectedRow();
        String codigo = tablaDepartamentos.getValueAt(fila, 0).toString();
        
        dm.PasarDatosTablasACampos(fila, codigo, txtIdDepartmaneto, txtDireccion, txtCosto, txtEstado, txtDescripcion, txtOrientacion, txtEstacionamiento, txtNumHabitaciones, txtNumBaños, txtNumEstacionamientos);
    }//GEN-LAST:event_tablaDepartamentosMouseClicked

    private void btnCargarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarTablaActionPerformed
        
        dm.cargarTablaDepartamentos(tablaDepartamentos);
    }//GEN-LAST:event_btnCargarTablaActionPerformed

    private void btonAgregarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonAgregarDepartamentoActionPerformed
        Region region = (Region) cmBoxRegion.getSelectedItem();
        Provincia provincia = (Provincia) cmBoxProvincia.getSelectedItem();
        Comuna comuna = (Comuna) cmBoxComuna.getSelectedItem();
        if (txtDireccion.getText().equals("") || txtCosto.getText().equals("") || txtEstado.getText().equals("") || txtDescripcion.getText().equals("")
                || txtOrientacion.getText().equals("") || txtEstacionamiento.getText().equals("") || txtNumHabitaciones.getText().equals("") || txtNumBaños.getText().equals("") || txtNumEstacionamientos.getText().equals("") || cmBoxComuna.getSelectedIndex() == 0 || cmBoxProvincia.getSelectedIndex() == 0 || cmBoxRegion.getSelectedIndex() == 0
                || comuna == null || provincia == null || region == null || txtContribucion.getText().equals("") || txtDividendo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Porfavor rellene todos los campos");
        } else if (!txtCosto.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "El campo costo solo acepta numeros");
        } else if (!txtNumHabitaciones.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "El campo numHabitaciones solo acepta numeros");
        } else if (!txtNumBaños.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "El campo numBaños solo acepta numeros");
        } else if (!txtNumEstacionamientos.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "El numEstacionamientos costo solo acepta numeros");
        } else {
            dm.agregarDepartamento(txtDireccion, txtCosto, txtEstado, txtDescripcion, txtOrientacion, txtEstacionamiento, txtNumHabitaciones, txtNumBaños, txtNumEstacionamientos, comuna.getIdComuna(), provincia.getIdProvincia(), region.getIdRegion(), txtDividendo, txtContribucion);
            dm.cargarTablaDepartamentos(tablaDepartamentos);
        }
        
    }//GEN-LAST:event_btonAgregarDepartamentoActionPerformed

    private void cmBoxRegionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmBoxRegionItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Region region = (Region) cmBoxRegion.getSelectedItem();
            
            Provincia provincia = new Provincia();
            DefaultComboBoxModel modeloComboProvincias = new DefaultComboBoxModel(dm.mostrarProvincias(region.getIdRegion()));
            cmBoxProvincia.setModel(modeloComboProvincias);
        }
    }//GEN-LAST:event_cmBoxRegionItemStateChanged

    private void cmBoxProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmBoxProvinciaItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            Provincia provincia = (Provincia) cmBoxProvincia.getSelectedItem();
            Comuna comuna = new Comuna();
            DefaultComboBoxModel modeloComboComunas = new DefaultComboBoxModel(dm.mostrarComunas(provincia.getIdProvincia()));
            cmBoxComuna.setModel(modeloComboComunas);
        }
    }//GEN-LAST:event_cmBoxProvinciaItemStateChanged

    private void btonActualizarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonActualizarDepartamentoActionPerformed
        Region region = (Region) cmBoxRegion.getSelectedItem();
        Provincia provincia = (Provincia) cmBoxProvincia.getSelectedItem();
        Comuna comuna = (Comuna) cmBoxComuna.getSelectedItem();
        
        if (txtDireccion.getText().equals("") || txtCosto.getText().equals("") || txtEstado.getText().equals("") || txtDescripcion.getText().equals("")
                || txtOrientacion.getText().equals("") || txtEstacionamiento.getText().equals("") || txtNumHabitaciones.getText().equals("") || txtNumBaños.getText().equals("") || txtNumEstacionamientos.getText().equals("") || cmBoxComuna.getSelectedIndex() == 0 || cmBoxProvincia.getSelectedIndex() == 0 || cmBoxRegion.getSelectedIndex() == 0
                || comuna == null || provincia == null || region == null) {
            JOptionPane.showMessageDialog(null, "Porfavor rellene todos los campos para actualizar");
        } else if (!txtCosto.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "El campo costo solo acepta numeros");
        } else if (!txtNumHabitaciones.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "El campo numHabitaciones solo acepta numeros");
        } else if (!txtNumBaños.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "El campo numBaños solo acepta numeros");
        } else if (!txtNumEstacionamientos.getText().matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "El numEstacionamientos costo solo acepta numeros");
        } else {
            dm.ActualizarDepartamentoo(txtDireccion, txtCosto, txtEstado, txtDescripcion, txtOrientacion, txtEstacionamiento, txtNumHabitaciones, txtNumBaños, txtNumEstacionamientos, comuna.getIdComuna(), provincia.getIdProvincia(), region.getIdRegion(), txtIdDepartmaneto);
            dm.cargarTablaDepartamentos(tablaDepartamentos);
        }
    }//GEN-LAST:event_btonActualizarDepartamentoActionPerformed

    private void btonEliminarDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btonEliminarDepartamentoActionPerformed
        if (txtIdDepartmaneto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe ingresar el id del departamento");
        } else {
            dm.EliminarDepartamento(txtIdDepartmaneto);
            dm.cargarTablaDepartamentos(tablaDepartamentos);
        }
    }//GEN-LAST:event_btonEliminarDepartamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaDepartamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCargarTabla;
    public javax.swing.JButton btonActualizarDepartamento;
    public javax.swing.JButton btonAgregarDepartamento;
    public javax.swing.JButton btonEliminarDepartamento;
    public javax.swing.JComboBox<String> cmBoxComuna;
    public javax.swing.JComboBox<String> cmBoxProvincia;
    public javax.swing.JComboBox<String> cmBoxRegion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tablaDepartamentos;
    private javax.swing.JTextField txtContribucion;
    public javax.swing.JTextField txtCosto;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDividendo;
    public javax.swing.JTextField txtEstacionamiento;
    public javax.swing.JTextField txtEstado;
    public javax.swing.JTextField txtIdDepartmaneto;
    public javax.swing.JTextField txtNumBaños;
    public javax.swing.JTextField txtNumEstacionamientos;
    public javax.swing.JTextField txtNumHabitaciones;
    public javax.swing.JTextField txtOrientacion;
    // End of variables declaration//GEN-END:variables
}
